#pragma once

#ifndef CRAND_VERSION_MAJOR
#define CRAND_VERSION_MAJOR 1
#endif
#ifndef CRAND_VERSION_MINOR
#define CRAND_VERSION_MINOR 0
#endif
#ifndef CRAND_VERSION_PATCH
#define CRAND_VERSION_PATCH 0
#endif